services:
  backend:
    image: gighub-backend:latest
    ports: ["8080:8080"]
    networks:
      - gighub_net
  frontend:
    image: gighub-frontend:latest
    ports: ["4200:80"]
    networks:
      - gighub_net
    depends_on: ["backend"]

networks:
  gighub_net:
